-- Pipeline jobs table.
-- UUID v7 IDs are generated by the application (time-ordered).
-- status and control are TEXT columns mapped to Rust enums via sqlx::Type.
-- The NOTIFY trigger fires on every INSERT or UPDATE so workers
-- using LISTEN can wake immediately rather than waiting for the poll interval.
CREATE TABLE IF NOT EXISTS pipeline_jobs (
    id                  UUID        PRIMARY KEY,
    job_type            TEXT        NOT NULL,
    job_key             TEXT        NOT NULL,
    pipeline_version    INT         NOT NULL DEFAULT 1,
    status              TEXT        NOT NULL DEFAULT 'ready',
    control             TEXT        NOT NULL DEFAULT 'none',
    current_step        TEXT        NOT NULL,
    step_data           JSONB       NOT NULL DEFAULT '{}',
    result              JSONB       NOT NULL DEFAULT '{}',
    tried               INT         NOT NULL DEFAULT 0,
    max_retries         INT         NOT NULL DEFAULT 0,
    retry_delay_secs    INT         NOT NULL DEFAULT 0,
    priority            INT         NOT NULL DEFAULT 0,
    wakeup_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    step_started_at     TIMESTAMPTZ,
    step_completed_at   TIMESTAMPTZ,
    timeout_at          TIMESTAMPTZ,
    worker_id           TEXT,
    last_heartbeat_at   TIMESTAMPTZ,
    progress            JSONB,
    error               TEXT,
    created_by          TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_ready
    ON pipeline_jobs (priority DESC, wakeup_at ASC)
    WHERE status = 'ready' AND control = 'none';

CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_key
    ON pipeline_jobs (job_type, job_key);

CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_running_timeout
    ON pipeline_jobs (timeout_at ASC)
    WHERE status = 'running' AND timeout_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_running_heartbeat
    ON pipeline_jobs (last_heartbeat_at ASC)
    WHERE status = 'running';

CREATE UNIQUE INDEX IF NOT EXISTS idx_pipeline_jobs_unique_active
    ON pipeline_jobs (job_type, job_key)
    WHERE status NOT IN ('completed', 'cancelled');

CREATE OR REPLACE FUNCTION pipeline_jobs_notify() RETURNS trigger AS $$
BEGIN
    PERFORM pg_notify('pipeline_jobs_changed', NEW.id::text);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS pipeline_jobs_changed ON pipeline_jobs;
CREATE TRIGGER pipeline_jobs_changed
    AFTER INSERT OR UPDATE ON pipeline_jobs
    FOR EACH ROW EXECUTE FUNCTION pipeline_jobs_notify();
